name: Generate SVGs

on:
  push:
    branches:
      - main  # mainブランチにプッシュしたときに実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Pythonのバージョンを指定

      - name: Install dependencies
        run: |
          pip install svgwrite

      - name: Run script
        run: |
          python create_kanji_svg.py

      - name: Upload SVG files
        uses: actions/upload-artifact@v3  # v3に変更
        with:
          name: svg-files
          path: svg_files/
